### ISSUE TITLE
Wrong Python version with Ubuntu in Dockerfile

### ISSUE THREAD

**Issue by thebiertrix** [HewlettPackard/X-TIME#21]
When building and running the docker container with WSL2, Ubuntu 20.04.6, Python 2 is the default version (i.e., /usr/bin/python is python2, python-config is python2-config). This breaks part of the Python scripts, e.g., test_general.py will not execute as it was written with Python 3 syntax. sst will query the detault Python version with python-config.
To make Python 3 the default version, the following changes to the dockerfile resolved the issue for me:+

```
RUN apt-get install --yes python python2 python3 python3-dev

RUN apt-get install --yes python-is-python3
...
RUN apt-get install --yes\
        python3-numpy
```

**Comment by gpedretti** [comment]
Thanks for raising the issue. Could you specify which DockerFile are you referring to?
